"""Configuration for Chirp3 HD voices and languages."""

CHIRP3_HD_VOICES = [
    "Achernar",
    "Achird",
    "Algenib",
    "Algieba",
    "Alnilam",
    "Aoede",
    "Autonoe",
    "Callirrhoe",
    "Charon",
    "Despina",
    "Enceladus",
    "Erinome",
    "Fenrir",
    "Gacrux",
    "Iapetus",
    "Kore",
    "Laomedeia",
    "Leda",
    "Orus",
    "Pulcherrima",
    "Puck",
    "Rasalgethi",
    "Sadachbia",
    "Sadaltager",
    "Schedar",
    "Sulafat",
    "Umbriel",
    "Vindemiatrix",
    "Zephyr",
    "Zubenelgenubi",
]

CHIRP3_HD_ENCODINGS = {
    "X-SAMPA": "PHONETIC_ENCODING_X_SAMPA",
    "IPA": "PHONETIC_ENCODING_IPA",
    "Pinyin": "PHONETIC_ENCODING_PINYIN",
    "Japanese": "PHONETIC_ENCODING_JAPANESE_YOMIGANA",
}

CHIRP3_HD_LANGUAGES = {
    "Arabic (Generic)": "ar-XA",
    "Bengali (India)": "bn-IN",
    "Danish (Denmark)": "da-DK",
    "Dutch (Belgium)": "nl-BE",
    "Dutch (Netherlands)": "nl-NL",
    "English (Australia)": "en-AU",
    "English (India)": "en-IN",
    "English (United Kingdom)": "en-GB",
    "English (United States)": "en-US",
    "Finnish (Finland)": "fi-FI",
    "French (Canada)": "fr-CA",
    "French (France)": "fr-FR",
    "German (Germany)": "de-DE",
    "Gujarati (India)": "gu-IN",
    "Hindi (India)": "hi-IN",
    "Indonesian (Indonesia)": "id-ID",
    "Italian (Italy)": "it-IT",
    "Japanese (Japan)": "ja-JP",
    "Kannada (India)": "kn-IN",
    "Korean (South Korea)": "ko-KR",
    "Malayalam (India)": "ml-IN",
    "Mandarin Chinese (China)": "cmn-CN",
    "Marathi (India)": "mr-IN",
    "Norwegian Bokmål (Norway)": "nb-NO",
    "Polish (Poland)": "pl-PL",
    "Portuguese (Brazil)": "pt-BR",
    "Russian (Russia)": "ru-RU",
    "Spanish (Spain)": "es-ES",
    "Spanish (United States)": "es-US",
    "Swahili (Kenya)": "sw-KE",
    "Swedish (Sweden)": "sv-SE",
    "Tamil (India)": "ta-IN",
    "Telugu (India)": "te-IN",
    "Thai (Thailand)": "th-TH",
    "Turkish (Turkey)": "tr-TR",
    "Ukrainian (Ukraine)": "uk-UA",
    "Urdu (India)": "ur-IN",
    "Vietnamese (Vietnam)": "vi-VN",
}
